import nx from '@nx/eslint-plugin';
import angular from 'angular-eslint';

/**
 * Workspace-root ESLint flat config.
 *
 * - Nx base/TypeScript/JavaScript configs provide the shared rule set and the
 *   `@nx/enforce-module-boundaries` rule. The Rendara dependency constraints
 *   below encode brief §4 exactly, across two tag dimensions:
 *     - `scope:*` — the layer chain (schema -> engine -> renderer -> viewer;
 *       ui-kit is self-contained; apps depend inward only). This is the
 *       authoritative §4 encoding and what the boundary QA exercises.
 *     - `type:*`  — defense-in-depth role rules (nothing imports an app; utils
 *       stay leaf). Every legal §4 edge satisfies both dimensions.
 *   See docs/architecture/module-boundaries.md for the table and the
 *   illegal-import verification procedure.
 * - angular-eslint contributes Angular component/template rules. Per-project
 *   configs generated by `@nx/angular` extend this file.
 */
export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    ignores: [
      '**/dist',
      '.nx',
      '.angular',
      'tmp',
      // The E9-S7 clean-room fixture is a standalone external Angular app with
      // its own tsconfig — outside the workspace's type-aware lint program.
      'tools/clean-room/fixture/**',
      '**/vitest.config.*.timestamp*',
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: [
            '^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$',
            // Shared test tooling (e.g. the axe e2e helper) lives in
            // `tools/testing/`, outside the layer chain. Allowing specs to
            // import it does not relax the §4 scope/type constraints below.
            '^.*tools/testing/.*$',
          ],
          depConstraints: [
            // --- scope: the layer chain (brief §4, authoritative). Each scope
            // lists every layer it may import, including itself. ---
            {
              sourceTag: 'scope:schema',
              onlyDependOnLibsWithTags: ['scope:schema'],
            },
            {
              sourceTag: 'scope:engine',
              onlyDependOnLibsWithTags: ['scope:schema', 'scope:engine'],
            },
            {
              sourceTag: 'scope:renderer',
              onlyDependOnLibsWithTags: ['scope:schema', 'scope:engine', 'scope:renderer'],
            },
            {
              sourceTag: 'scope:viewer',
              onlyDependOnLibsWithTags: [
                'scope:schema',
                'scope:engine',
                'scope:renderer',
                'scope:viewer',
              ],
            },
            {
              // ui-kit is designer-only shared UI; it depends on no report layer.
              sourceTag: 'scope:ui-kit',
              onlyDependOnLibsWithTags: ['scope:ui-kit'],
            },
            {
              sourceTag: 'scope:designer',
              onlyDependOnLibsWithTags: [
                'scope:schema',
                'scope:engine',
                'scope:renderer',
                'scope:ui-kit',
                'scope:designer',
              ],
            },
            {
              // viewer-demo proves the integration story: viewer only.
              sourceTag: 'scope:viewer-demo',
              onlyDependOnLibsWithTags: ['scope:viewer', 'scope:viewer-demo'],
            },
            // --- type: role-based defense-in-depth (consistent with scope). ---
            {
              sourceTag: 'type:app',
              onlyDependOnLibsWithTags: [
                'type:feature',
                'type:ui',
                'type:util',
                'type:publishable',
              ],
            },
            {
              sourceTag: 'type:publishable',
              onlyDependOnLibsWithTags: ['type:feature', 'type:util', 'type:publishable'],
            },
            {
              sourceTag: 'type:feature',
              onlyDependOnLibsWithTags: [
                'type:feature',
                'type:ui',
                'type:util',
                'type:publishable',
              ],
            },
            {
              sourceTag: 'type:ui',
              onlyDependOnLibsWithTags: ['type:ui', 'type:util'],
            },
            {
              sourceTag: 'type:util',
              onlyDependOnLibsWithTags: ['type:util'],
            },
          ],
        },
      ],
    },
  },
  // Angular component/directive TypeScript rules.
  ...angular.configs.tsRecommended.map((config) => ({
    ...config,
    files: ['**/*.ts'],
  })),
  {
    files: ['**/*.ts'],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'rdr', style: 'camelCase' },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'rdr', style: 'kebab-case' },
      ],
    },
  },
  // Angular template (HTML) rules, including accessibility.
  ...angular.configs.templateRecommended.map((config) => ({
    ...config,
    files: ['**/*.html'],
  })),
  ...angular.configs.templateAccessibility.map((config) => ({
    ...config,
    files: ['**/*.html'],
  })),
];
